[package]
name = "rua"
version = "0.1.0"
authors = ["rgb-24bit <'rgb-24bit@foxmail.com'>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4"

