[package]
name = "rua"
version = "0.1.0"
authors = ["rgb-24bit <'rgb-24bit@foxmail.com'>"]
edition = "2018"

[workspace]

members = [
    "algorithm",
]

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4"
anyhow = "1.0.41"
fasteval = "0.2.4"
